# -*- coding: utf-8 -*-
"""dataFusionAndExplanation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14twHzkP-CCS-RVvJ-tnotr6Lv3QfjCGx
"""

import numpy as np
import pandas as pd
import json

weights={'text':0.5,'image':0.3,'video':0.2}

def calculate_weight(results:list[dict]):
  weight_coeff=0
  for result in results:
    weight_coeff+=weights[result['modality']]*result['confidence']
  return round(weight_coeff,2)

def decide_verdict(score:float):
  if score>0.7:
    return 'Real'
  elif score>0.3:
    return 'Uncertain'
  else:
    return 'Fake'

def get_best_evidence(results:list[dict]):
  return max(results,key=lambda x:x['confidence'])['evidence'][0]

def fuse_and_explain(results:list[dict]):
  final_confidence=calculate_weight(results)
  final_verdict=decide_verdict(final_confidence)
  best_evidence=get_best_evidence(results)
  explanation=f"The Claim {results[0]['claim']} is marked as {final_verdict} because The supporting sources indicates : {best_evidence}"
  return json.dumps({
      "verdict":final_verdict,
      "confidence":final_confidence,
      "explanation":explanation
  })

if __name__ == "__main__":
  text_result = {
    "modality": "text",
    "claim": "WHO approved herbal cure for COVID-19.",
    "verdict": "Fake",
    "confidence": 0.25,
    "evidence": ["WHO has not approved any herbal cure for COVID-19."]
  }

  image_result = {
    "modality": "image",
    "claim": "WHO approved herbal cure for COVID-19.",
    "verdict": "Fake",
    "confidence": 0.35,
    "evidence": ["Official sources show WHO denied herbal cure claims."]
  }

  video_result = {
    "modality": "video",
    "claim": "WHO approved herbal cure for COVID-19.",
    "verdict": "Uncertain",
    "confidence": 0.55,
    "evidence": ["No official WHO announcement found."]
  }
  print(fuse_and_explain([text_result,image_result,video_result]))